// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeHub.API.Data;

#nullable disable

namespace TradeHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726173535_AddLowStock")]
    partial class AddLowStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeHub.API.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bose"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dyson"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 7,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 8,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 9,
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Zara"
                        },
                        new
                        {
                            Id = 11,
                            Name = "H&M"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Casio"
                        },
                        new
                        {
                            Id = 13,
                            Name = "IKEA"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Philips"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Penguin Books"
                        },
                        new
                        {
                            Id = 16,
                            Name = "O'Reilly Media"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gymshark"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Garmin"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Decathlon"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Starbucks"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Decor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RelatedOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedProductId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NewOrder");

                    b.HasKey("Id");

                    b.HasIndex("RelatedOrderId");

                    b.HasIndex("RelatedProductId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 448.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 6, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 129.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 89.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 7, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            TotalPrice = 549.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2026, 7, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            TotalPrice = 279.98m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2026, 7, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalPrice = 193.99m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2026, 7, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalPrice = 84.50m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2026, 7, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalPrice = 159.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            OrderDate = new DateTime(2026, 7, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalPrice = 72.49m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            OrderDate = new DateTime(2026, 7, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            TotalPrice = 249.50m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 149.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 549.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 5,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 5,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 49.00m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 44.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 6,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 249.50m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 7,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 32.50m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 7,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 24.00m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 7,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 159.00m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 9,
                            ProductId = 19,
                            Quantity = 2,
                            UnitPrice = 24.00m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 9,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 42.00m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 10,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 249.50m
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium over-ear wireless headphones with 40-hour battery life and active noise cancellation.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Aether Sound Wave Wireless Headphones",
                            Price = 299.99m,
                            StockQuantity = 45,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact TKL mechanical keyboard with per-key RGB lighting and PBT keycaps.",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Vanguard Ergonomic Mechanical Keyboard",
                            Price = 149.00m,
                            StockQuantity = 80,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IPS panel monitor with 144Hz refresh rate, 1ms response time, and USB-C PD 65W charging.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "ProView 4K Ultra HD Monitor 27\"",
                            Price = 549.00m,
                            StockQuantity = 22,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced biometric ring tracking heart rate, sleep stages, SpO2, and recovery scores.",
                            ImageUrl = "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Pulse Pro Smart Fitness Tracking Ring",
                            Price = 159.00m,
                            StockQuantity = 60,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "True wireless earbuds with spatial audio, IPX7 water resistance, and wireless charging case.",
                            ImageUrl = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Orion Pro ANC Earbuds",
                            Price = 189.99m,
                            StockQuantity = 110,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra-lightweight gaming mouse with 26K DPI optical sensor and PTFE feet.",
                            ImageUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Apex Precision Wireless Mouse",
                            Price = 79.99m,
                            StockQuantity = 140,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "360-degree immersive sound with deep bass, 24-hour playtime, and IP67 dust/water rating.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "CinemaSound Portable Bluetooth Speaker",
                            Price = 119.00m,
                            StockQuantity = 95,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra-compact fast charger for laptops, tablets, and phones simultaneously.",
                            ImageUrl = "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Nexus 100W Multi-Port USB-C GaN Charger",
                            Price = 69.50m,
                            StockQuantity = 180,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Screen-bar monitor light with dual ambient backlighting and smart auto-dimming sensor.",
                            ImageUrl = "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Aura Desk RGB Smart Ambient Lightbar",
                            Price = 89.99m,
                            StockQuantity = 70,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1080p 60fps streaming webcam with autofocus, dual noise-canceling mics, and privacy shutter.",
                            ImageUrl = "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "StreamCraft HD Pro Web Camera 1080p",
                            Price = 99.00m,
                            StockQuantity = 65,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rugged aluminum external SSD with read speeds up to 2000MB/s and drop protection.",
                            ImageUrl = "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "TitanShield 2TB NVMe Portable SSD",
                            Price = 179.99m,
                            StockQuantity = 85,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable aluminum laptop riser with built-in quiet dual cooling fans.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "VaporCool Ergonomic Laptop Stand",
                            Price = 49.99m,
                            StockQuantity = 130,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium full-grain leather bomber jacket with quilted lining and custom YKK zippers.",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Apex Leather Bomber Jacket",
                            Price = 249.50m,
                            StockQuantity = 35,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight runners with responsive foam sole and breathable engineered mesh upper.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Urban Streetwear Performance Sneakers",
                            Price = 129.99m,
                            StockQuantity = 120,
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% premium Oxford cotton shirt with a tailored slim fit, perfect for business casual.",
                            ImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Classic Oxford Button-Down Shirt",
                            Price = 79.00m,
                            StockQuantity = 200,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant mid-length wool trench coat with double-breasted button closure.",
                            ImageUrl = "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Nordic Minimalist Wool Blend Coat",
                            Price = 219.00m,
                            StockQuantity = 40,
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handmade 100% Mulberry silk tie set with matching pocket square and cuff links.",
                            ImageUrl = "https://images.unsplash.com/photo-1589756823695-278bc923f962?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Heritage Italian Silk Necktie Set",
                            Price = 59.99m,
                            StockQuantity = 90,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Titanium frame sunglasses with TAC 100% UV400 anti-glare polarized lenses.",
                            ImageUrl = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Vanguard Aviator Polarized Sunglasses",
                            Price = 139.00m,
                            StockQuantity = 75,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water-resistant heavy canvas weekender travel bag with genuine leather trim.",
                            ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Urban Commuter Canvas Duffle Bag",
                            Price = 109.50m,
                            StockQuantity = 60,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra-soft 100% Mongolian cashmere crewneck sweater for cold weather warmth.",
                            ImageUrl = "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "AeroSoft Cashmere Knit Sweater",
                            Price = 169.00m,
                            StockQuantity = 50,
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sapphire crystal glass timepiece with 21-jewel Japanese automatic movement.",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Chronos Automatic Minimalist Wristwatch",
                            Price = 289.00m,
                            StockQuantity = 30,
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tunable white and color smart lamp with app control, voice assistant support, and 16M color options.",
                            ImageUrl = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Iris Smart Ambient Light & Lamp",
                            Price = 59.99m,
                            StockQuantity = 90,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 14,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultrasonic aromatherapy diffuser with 7 ambient LED colors and auto shut-off.",
                            ImageUrl = "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Lumina Ceramic Essential Oil Diffuser",
                            Price = 45.00m,
                            StockQuantity = 75,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handcrafted organizer set combining Italian marble and solid walnut for a premium workspace.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Marble & Walnut Desk Organizer Set",
                            Price = 89.00m,
                            StockQuantity = 40,
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft cotton woven throw blanket with fringe detail, perfect for sofa styling.",
                            ImageUrl = "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Zenith Hand-Woven Boho Throw Blanket",
                            Price = 49.99m,
                            StockQuantity = 110,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 3 matte textured stoneware vases designed for pampas grass and dried blooms.",
                            ImageUrl = "https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Artisan Ceramic Flower Vase Trio",
                            Price = 64.00m,
                            StockQuantity = 85,
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Silent non-ticking sweep movement clock crafted from natural solid teak wood.",
                            ImageUrl = "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Mid-Century Wooden Wall Clock 12\"",
                            Price = 55.00m,
                            StockQuantity = 95,
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hand-poured soy candle with notes of cedarwood, amber, and wild lavender in a glass jar.",
                            ImageUrl = "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Botanical Soy Wax Scented Candle",
                            Price = 28.50m,
                            StockQuantity = 200,
                            SubcategoryId = 12
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 13,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 2 heavy-duty oak floating shelves with hidden mounting brackets.",
                            ImageUrl = "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Minimalist Floating Wooden Wall Shelves",
                            Price = 74.99m,
                            StockQuantity = 65,
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In-depth guide covering distributed systems, microservices, event-driven architecture, and cloud-native patterns.",
                            ImageUrl = "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Modern Web Architecture & Systems",
                            Price = 39.99m,
                            StockQuantity = 150,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Essential reading on UX principles, cognitive affordances, and designing intuitive product experiences.",
                            ImageUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "The Design of Everyday Systems & Interfaces",
                            Price = 49.00m,
                            StockQuantity = 100,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Robert C. Martin's classic guide to writing readable, maintainable, and testable code.",
                            ImageUrl = "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Clean Code: A Handbook of Agile Craftsmanship",
                            Price = 44.99m,
                            StockQuantity = 85,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive technical reference on advanced C# language features, async programming, and memory tuning.",
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Mastering C# 12 & .NET 9 High Performance",
                            Price = 59.99m,
                            StockQuantity = 120,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peter Thiel's groundbreaking book on how to build companies that create new things.",
                            ImageUrl = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Zero to One: Notes on Startups and Future",
                            Price = 27.00m,
                            StockQuantity = 175,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "James Clear's framework for improving every day through tiny changes and system building.",
                            ImageUrl = "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Atomic Habits: An Easy & Proven Way",
                            Price = 24.99m,
                            StockQuantity = 220,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 16,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Martin Kleppmann's authoritative guide to data systems architecture, scalability, and fault tolerance.",
                            ImageUrl = "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Designing Data-Intensive Applications",
                            Price = 54.50m,
                            StockQuantity = 90,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeless lessons on wealth, greed, and happiness by Morgan Housel.",
                            ImageUrl = "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "The Psychology of Money",
                            Price = 22.00m,
                            StockQuantity = 140,
                            SubcategoryId = 15
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial-grade hex dumbbells with non-slip rubber coating and ergonomic contoured handles.",
                            ImageUrl = "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Titan Rubber Hex Dumbbell Set (2x 15kg)",
                            Price = 89.99m,
                            StockQuantity = 55,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latex resistance bands in 5 progressive tension levels for home workout, rehab, and mobility training.",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "AeroGrip Resistance Band Set (5 Levels)",
                            Price = 34.99m,
                            StockQuantity = 200,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carbon fiber plate running shoes with ZoomX foam for elite race-day performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "VitalStride Pro Running Shoes",
                            Price = 219.00m,
                            StockQuantity = 65,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 18,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wi-Fi connected smart scale measuring 17 body metrics including muscle mass, visceral fat, and bone density.",
                            ImageUrl = "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "SmartScale Pro Body Composition Analyzer",
                            Price = 79.99m,
                            StockQuantity = 48,
                            SubcategoryId = 20
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Extra thick non-slip alignment yoga mat with carrying strap.",
                            ImageUrl = "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "FlexCore Eco-Friendly TPE Yoga Mat 6mm",
                            Price = 42.50m,
                            StockQuantity = 130,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 19,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tangle-free steel cable speed jump rope with aluminum anti-slip handles.",
                            ImageUrl = "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Pulse Speed Bearing Skipping Jump Rope",
                            Price = 19.99m,
                            StockQuantity = 190,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 18,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Powerful brushless motor muscle recovery massage gun with 6 interchangeable heads.",
                            ImageUrl = "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "TheraGun Deep Tissue Percussion Massager",
                            Price = 149.00m,
                            StockQuantity = 70,
                            SubcategoryId = 17
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Double-wall vacuum insulated water bottle keeping drinks cold for 24 hours.",
                            ImageUrl = "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "HydroMax 1.5L Insulated Stainless Steel Bottle",
                            Price = 38.00m,
                            StockQuantity = 160,
                            SubcategoryId = 18
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Single-origin Ethiopian Yirgacheffe beans, dark roast, with tasting notes of dark chocolate and blackberry.",
                            ImageUrl = "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Terra Espresso Roast Artisan Coffee Beans (1kg)",
                            Price = 32.50m,
                            StockQuantity = 300,
                            SubcategoryId = 21
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium blended herbal teas sourced from Swiss Alpine meadows — 60 enveloped sachets.",
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Organic Alpine Herbal Tea Reserve Selection",
                            Price = 24.00m,
                            StockQuantity = 250,
                            SubcategoryId = 21
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stone-ground first-harvest Japanese ceremonial matcha with vibrant green color and umami sweetness.",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Matcha Ceremonial Grade (100g Tin)",
                            Price = 42.00m,
                            StockQuantity = 180,
                            SubcategoryId = 21
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Steeped for 24 hours from organic specialty Arabica beans. Bold, smooth, and low acidity.",
                            ImageUrl = "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Artisan Cold Brew Coffee Concentrate (1L)",
                            Price = 18.99m,
                            StockQuantity = 140,
                            SubcategoryId = 22
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Refreshing sparkling tonic infused with ashwagandha, elderberry, and hibiscus.",
                            ImageUrl = "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Sparkling Botanical Adaptogen Tonic 12-Pack",
                            Price = 36.00m,
                            StockQuantity = 110,
                            SubcategoryId = 22
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warming blend of organic turmeric, ginger, cinnamon, and black pepper for golden milk.",
                            ImageUrl = "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Golden Milk Turmeric Latte Blend (250g)",
                            Price = 22.50m,
                            StockQuantity = 150,
                            SubcategoryId = 21
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upcycled dried coffee cherries delivering a sweet, fruity tea rich in antioxidants.",
                            ImageUrl = "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Pure Cascara Coffee Cherry Tea (200g)",
                            Price = 19.50m,
                            StockQuantity = 120,
                            SubcategoryId = 21
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "The active noise cancellation is unreal! Worth every penny.",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Super comfortable for long coding sessions. Battery lasts for days.",
                            CreatedAt = new DateTime(2026, 6, 5, 14, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Tactile feel is great. RGB software could be slightly better.",
                            CreatedAt = new DateTime(2026, 6, 6, 11, 20, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 4,
                            UserId = 15
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Colors are vibrant and 144Hz makes everything buttery smooth.",
                            CreatedAt = new DateTime(2026, 6, 8, 16, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Rating = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Sleep tracking insights helped me improve my bedtime routine significantly.",
                            CreatedAt = new DateTime(2026, 6, 10, 9, 15, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Rating = 5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Genuine leather smelling amazing. Fits like a glove!",
                            CreatedAt = new DateTime(2026, 6, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 5,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Very lightweight shoes, perfect for daily morning runs.",
                            CreatedAt = new DateTime(2026, 6, 14, 8, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Rating = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Fabric quality is superb. Doesn't wrinkle easily after wash.",
                            CreatedAt = new DateTime(2026, 6, 15, 12, 10, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Rating = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            Comment = "App control is super seamless. Love the warmth modes for nighttime.",
                            CreatedAt = new DateTime(2026, 6, 18, 20, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Rating = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Fills the living room with nice lavender scent in minutes.",
                            CreatedAt = new DateTime(2026, 6, 20, 15, 20, 0, 0, DateTimeKind.Utc),
                            ProductId = 9,
                            Rating = 4,
                            UserId = 17
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Must-read for modern backend developers. Clear code examples.",
                            CreatedAt = new DateTime(2026, 6, 22, 13, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 11,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Comment = "A timeless classic. Changed how I structure my C# methods.",
                            CreatedAt = new DateTime(2026, 6, 24, 17, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 13,
                            Rating = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Heft and grip are perfect. No chemical smell on the rubber.",
                            CreatedAt = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 14,
                            Rating = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Rich crema and smooth dark chocolate notes. Best morning espresso!",
                            CreatedAt = new DateTime(2026, 6, 28, 7, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = 18,
                            Rating = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Vibrant bright green color, zero bitterness. High quality grade.",
                            CreatedAt = new DateTime(2026, 6, 29, 10, 10, 0, 0, DateTimeKind.Utc),
                            ProductId = 20,
                            Rating = 5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Noise isolation rivals over-ear models. Bass response is crisp.",
                            CreatedAt = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 21,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Mouse sensor is spot-on for FPS games. Glides effortlessly.",
                            CreatedAt = new DateTime(2026, 7, 2, 19, 20, 0, 0, DateTimeKind.Utc),
                            ProductId = 22,
                            Rating = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Charges my MacBook and phone at full speed from one wall plug.",
                            CreatedAt = new DateTime(2026, 7, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 24,
                            Rating = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Heavy wool blend keeps me warm in freezing wind. Top tier craftsmanship.",
                            CreatedAt = new DateTime(2026, 7, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 29,
                            Rating = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            Comment = "The automatic rotor movement is visible through back case. Stunning watch.",
                            CreatedAt = new DateTime(2026, 7, 9, 21, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 34,
                            Rating = 5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Beautiful minimalist aesthetic for my dining table setup.",
                            CreatedAt = new DateTime(2026, 7, 11, 13, 10, 0, 0, DateTimeKind.Utc),
                            ProductId = 36,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Deep dive into .NET 9 performance tuning. Highly recommended!",
                            CreatedAt = new DateTime(2026, 7, 12, 15, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = 40,
                            Rating = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Life-changing practical advice on habit formation.",
                            CreatedAt = new DateTime(2026, 7, 14, 18, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 42,
                            Rating = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Melts away leg soreness after intense leg day workouts.",
                            CreatedAt = new DateTime(2026, 7, 16, 20, 15, 0, 0, DateTimeKind.Utc),
                            ProductId = 47,
                            Rating = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Smooth cold brew with zero harshness. Add oat milk for perfection.",
                            CreatedAt = new DateTime(2026, 7, 18, 8, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 49,
                            Rating = 5,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Phones & Tablets",
                            Slug = "phones"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Computers & Laptops",
                            Slug = "laptops"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Home Appliances",
                            Slug = "appliances"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Audio & Gadgets",
                            Slug = "audio"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Men's Clothing",
                            Slug = "men"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Women's Clothing",
                            Slug = "women"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Shoes & Sneakers",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Furniture",
                            Slug = "furniture"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Lighting",
                            Slug = "lighting"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Kitchenware",
                            Slug = "kitchen"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Textiles & Bedding",
                            Slug = "textiles"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "Fiction & Novels",
                            Slug = "fiction"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Sci-Fi & Fantasy",
                            Slug = "scifi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Personal Dev.",
                            Slug = "personal"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Name = "Kids Books",
                            Slug = "kids"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Name = "Gym Equipment",
                            Slug = "gym"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Name = "Sportswear",
                            Slug = "sportswear"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Name = "Supplements",
                            Slug = "supplements"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Name = "Smart Wearables",
                            Slug = "wearables"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Name = "Hot Drinks",
                            Slug = "hot"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Name = "Cold Drinks",
                            Slug = "cold"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Name = "Energy Drinks",
                            Slug = "energy"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Name = "Organic Juices",
                            Slug = "organic"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vendora.store",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vendor@vendora.store",
                            FullName = "Vendor One Store",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "techworld@vendor.store",
                            FullName = "TechWorld Electronics",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "apexapparel@vendor.store",
                            FullName = "Apex Apparel Co",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lumina@vendor.store",
                            FullName = "Lumina Home & Living",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bookhaven@vendor.store",
                            FullName = "BookHaven Publishing",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fitpulse@vendor.store",
                            FullName = "FitPulse Athletics",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "artisan@vendor.store",
                            FullName = "Artisan Roasters",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nordic@vendor.store",
                            FullName = "Nordic Design Studio",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cyberedge@vendor.store",
                            FullName = "CyberEdge Gaming Labs",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ecostyle@vendor.store",
                            FullName = "EcoStyle Sustainable",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zenith@vendor.store",
                            FullName = "Zenith Acoustics",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buyer@vendora.store",
                            FullName = "John Buyer",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@buyer.com",
                            FullName = "Alice Vance",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@buyer.com",
                            FullName = "Bob Smith",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie@buyer.com",
                            FullName = "Charlie Brown",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana@buyer.com",
                            FullName = "Diana Prince",
                            PasswordHash = "$2a$11$imqp6dZtk9JTXGF99nHQeOG4a8Rn9JrnT0omiuOmTMHH31ukONRlG",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Notification", b =>
                {
                    b.HasOne("TradeHub.API.Models.Order", "RelatedOrder")
                        .WithMany()
                        .HasForeignKey("RelatedOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradeHub.API.Models.Product", "RelatedProduct")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedOrder");

                    b.Navigation("RelatedProduct");
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.HasOne("TradeHub.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeHub.API.Models.OrderItem", b =>
                {
                    b.HasOne("TradeHub.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeHub.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.HasOne("TradeHub.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TradeHub.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeHub.API.Models.Subcategory", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("TradeHub.API.Models.Review", b =>
                {
                    b.HasOne("TradeHub.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeHub.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeHub.API.Models.Subcategory", b =>
                {
                    b.HasOne("TradeHub.API.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TradeHub.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradeHub.API.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TradeHub.API.Models.Subcategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradeHub.API.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
