// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeHub.API.Data;

#nullable disable

namespace TradeHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeHub.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Decor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 448.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2026, 6, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 129.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2026, 6, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Delivered",
                            TotalPrice = 89.99m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2026, 7, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            TotalPrice = 549.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2026, 7, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Shipped",
                            TotalPrice = 279.98m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2026, 7, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalPrice = 193.99m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2026, 7, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalPrice = 84.50m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2026, 7, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalPrice = 159.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            OrderDate = new DateTime(2026, 7, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalPrice = 72.49m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            OrderDate = new DateTime(2026, 7, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            TotalPrice = 249.50m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 149.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 549.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 5,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 5,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 49.00m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 13,
                            Quantity = 1,
                            UnitPrice = 44.99m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 6,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 249.50m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 7,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 32.50m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 7,
                            ProductId = 19,
                            Quantity = 1,
                            UnitPrice = 24.00m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 7,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 159.00m
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 9,
                            ProductId = 19,
                            Quantity = 2,
                            UnitPrice = 24.00m
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 9,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 42.00m
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 10,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 249.50m
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium over-ear wireless headphones with 40-hour battery life and active noise cancellation.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Aether Sound Wave Wireless Headphones",
                            Price = 299.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact TKL mechanical keyboard with per-key RGB lighting and PBT keycaps.",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Vanguard Ergonomic Mechanical Keyboard",
                            Price = 149.00m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IPS panel monitor with 144Hz refresh rate, 1ms response time, and USB-C PD 65W charging.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "ProView 4K Ultra HD Monitor 27\"",
                            Price = 549.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced biometric ring tracking heart rate, sleep stages, SpO2, and recovery scores.",
                            ImageUrl = "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Pulse Pro Smart Fitness Tracking Ring",
                            Price = 159.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium full-grain leather bomber jacket with quilted lining and custom YKK zippers.",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Apex Leather Bomber Jacket",
                            Price = 249.50m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight runners with responsive foam sole and breathable engineered mesh upper.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Urban Streetwear Performance Sneakers",
                            Price = 129.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% premium Oxford cotton shirt with a tailored slim fit, perfect for business casual.",
                            ImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Classic Oxford Button-Down Shirt",
                            Price = 79.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tunable white and color smart lamp with app control, voice assistant support, and 16M color options.",
                            ImageUrl = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Iris Smart Ambient Light & Lamp",
                            Price = 59.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultrasonic aromatherapy diffuser with 7 ambient LED colors and auto shut-off.",
                            ImageUrl = "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Lumina Ceramic Essential Oil Diffuser",
                            Price = 45.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handcrafted organizer set combining Italian marble and solid walnut for a premium workspace.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Marble & Walnut Desk Organizer Set",
                            Price = 89.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In-depth guide covering distributed systems, microservices, event-driven architecture, and cloud-native patterns.",
                            ImageUrl = "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Modern Web Architecture & Systems (Hardcover)",
                            Price = 39.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Essential reading on UX principles, cognitive affordances, and designing intuitive product experiences.",
                            ImageUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "The Design of Everyday Systems & Interfaces",
                            Price = 49.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Robert C. Martin's classic guide to writing readable, maintainable, and testable code.",
                            ImageUrl = "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Clean Code: A Handbook of Agile Craftsmanship",
                            Price = 44.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial-grade hex dumbbells with non-slip rubber coating and ergonomic contoured handles.",
                            ImageUrl = "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Titan Rubber Hex Dumbbell Set (2x 15kg)",
                            Price = 89.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latex resistance bands in 5 progressive tension levels for home workout, rehab, and mobility training.",
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "AeroGrip Resistance Band Set (5 Levels)",
                            Price = 34.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carbon fiber plate running shoes with ZoomX foam for elite race-day performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "VitalStride Pro Running Shoes",
                            Price = 219.00m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wi-Fi connected smart scale measuring 17 body metrics including muscle mass, visceral fat, and bone density.",
                            ImageUrl = "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "SmartScale Pro Body Composition Analyzer",
                            Price = 79.99m,
                            StockQuantity = 48
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Single-origin Ethiopian Yirgacheffe beans, dark roast, with tasting notes of dark chocolate and blackberry.",
                            ImageUrl = "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Terra Espresso Roast Artisan Coffee Beans (1kg)",
                            Price = 32.50m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium blended herbal teas sourced from Swiss Alpine meadows — 60 enveloped sachets.",
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Organic Alpine Herbal Tea Reserve Selection",
                            Price = 24.00m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stone-ground first-harvest Japanese ceremonial matcha with vibrant green color and umami sweetness.",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop&q=60",
                            IsActive = true,
                            Name = "Matcha Ceremonial Grade (100g Tin)",
                            Price = 42.00m,
                            StockQuantity = 180
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vendora.store",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$5k5RfW7HkXfDGt8L.V1AZOQtJSvDz3FMK4l0B3f1Rr3DxBR2CzCaO",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vendor@vendora.store",
                            FullName = "Vendor One",
                            PasswordHash = "$2a$11$5k5RfW7HkXfDGt8L.V1AZOQtJSvDz3FMK4l0B3f1Rr3DxBR2CzCaO",
                            Role = "Vendor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buyer@vendora.store",
                            FullName = "John Buyer",
                            PasswordHash = "$2a$11$5k5RfW7HkXfDGt8L.V1AZOQtJSvDz3FMK4l0B3f1Rr3DxBR2CzCaO",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.HasOne("TradeHub.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeHub.API.Models.OrderItem", b =>
                {
                    b.HasOne("TradeHub.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeHub.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.HasOne("TradeHub.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TradeHub.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TradeHub.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TradeHub.API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TradeHub.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
